# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20161020_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
