# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_userproject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.UserProfile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
