# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_auto_20161022_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
