# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Page',
        ),
    ]
